baseURL = 'https://moshekaplan.com/'
languageCode = 'en-us'
title = "Moshe Kaplan's Blog"
theme = 'Hugo-Octopress'

[params]
  author = "Moshe Kaplan"
  # --- Start sidebar options ---
  # Number of last posts that will be displayed in the sidebar - set to 0 or remove to hide this section
  sidebarRecentLimit = 0

  # Sidebar header - passed to markdownify so you can write markdown here
  #sidebarHeader = "Sidebar Header"

  # Sidebar text also supports markdown
  # New lines can be added with two spaces at the end of line. New paragraphs can be added with two an empty line.
  # when adding two new lines, remember to remove the indentation otherwise the new line will be treated as a codeblock
  sidebarText = """
  ![image](/moshe.jpeg)
  Welcome!
  I'm Moshe Kaplan, a cybersecurity engineer in the DC area.
  This blog is where I share some of the things I've learned, usually related to programming or cybersecurity. 
  """
  # Sidebar menu - if true will add a sidebar menu between sidebar text and recent posts
  sidebarMenuEnabled = true
  #sidebarMenuHeader = "Sidebar Links"

  # sidebar links
  github = "https://github.com/moshekaplan"
  bitbucket = ""
  twitter = ""
  mastodon = ""
  keybase = ""
  stackoverflow = ""
  linkedin = "https://www.linkedin.com/in/moshekaplan1/"
  youtube = ""
  facebook = ""
  instagram = ""

  # If false, all of blog post will appear on front page (and in pagination)
  truncate = true
  description = "Moshe Kaplan's blog, usually about programming and cybersecurity"
  defaultKeywords = ["Moshe Kaplan" , "cybersecurity" , "programming" , "security"]

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
