baseURL = 'https://moshekaplan.com/'
languageCode = 'en-us'
title = "Moshe Kaplan's website"
theme = 'Hugo-Octopress'

[params]
  author = "Moshe Kaplan"

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
